# Generated by Django 4.2.4 on 2023-08-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
